server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    '[bdbe.bdbd]': INFO
    '[org.hibernate.type]': TRACE

proxy:
  host: krmp-proxy.9rum.cc
  port: 3128

cloud:
  aws:
    credentials:
      accessKey:  ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET_NAME}
    stack:
      auto: false
kakao:
  admin:
    key: ${KAKAOPAY_ADMIN_KEY}
payment:
  approval-url: https://ke1567c9038cca.user-app.krampoline.com/paymentwaiting
  cancel-url: https://ke1567c9038cca.user-app.krampoline.com/paymentfail
  fail-url: https://ke1567c9038cca.user-app.krampoline.com/paymentfail


# 파일 저장 경로
#file:
#  path: ./images/